version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.31
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: everglowsy_beautysalon
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    ports:
      - 3307:3306
    volumes:
      - $HOME/database:/var/lib/mysql
    networks:
      - apinetwork

  api-parkauto-app:
    container_name: everglowsystudioappcontainer
    build: .
    image: everglowsystudioapp:v1
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/everglowsy_beautysalon
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SERVICE_TAGS: prod
      SERVICE_NAME: springapi
    depends_on:
      - mysqldb
    networks:
      - apinetwork

networks:
  apinetwork:
    driver: bridge